description: An orb with some simple ways to help you with your first build.

jobs:
  hello-build:
    executor: default
    steps:
    - run:
        name: Skip when all ECR tags exist
        command: <<include(scripts/readme-update-check.sh)>>